design-docs: introduce rolling stock collections
OpenRailAssociation/osrd-website pull request #197
Opened 2024-05-13 15:43 UTC by multun

2024-05-13 19:56 UTC, leovalais approved these changes
LGTM as is, maybe a few endpoints could be useful as implementation guidelines. 

We could introduce the possibility of locking a collection upfront as this feature is likely to be requested down the line I believe.

2024-05-13 20:31 UTC, multun commented
There will be no need for locking once permissions are implemented: an infra is locked if nobody has writer or greater rights

2024-05-13 21:01 UTC, leovalais commented
> There will be no need for locking once permissions are implemented: an infra is locked if nobody has writer or greater rights

Ofc, you're right.

2024-05-13 22:00 UTC, multun commented
I've added a sample migration sql. I trust the implementer with coming up with the crud for this.

2024-08-30 22:29 UTC, SergeCroise requested changes
@multun , please review my suggestion

2024-08-30 23:15 UTC, multun commented
The suggestion is good but I can't apply it without closing this PR: I don't have push access to the repository anymore. I see two possible options:
- push to the branch yourself, and resolve your own comment
- I could fork, close this PR and open a new one

2024-09-20 08:53 UTC, woshilapin commented on content/docs/reference/design-docs/rolling-stock-collections.en.md
> +- a name
And probably an identifier? (but based on the `SQL` below, I guess the answer to my answer is yes)

2024-09-20 08:54 UTC, woshilapin commented on content/docs/reference/design-docs/rolling-stock-collections.en.md
> +  name text not null,
```sql
  description text not null,
```

2024-09-20 08:54 UTC, woshilapin commented on content/docs/reference/design-docs/rolling-stock-collections.en.md
> +
I guess we also would like to add a `rolling_stock_collection_id` to the `timetable` table, isn't it?

2024-12-10 16:56 UTC, flomonster commented
With the new permission model we've designed, it won't be necessary to have rolling stock groups.

2024-12-10 16:56 UTC, closed without merging